[server]
enableStaticServing = true

[[theme.fontFaces]]
family="Figtree"
url="app/static/Figtree-Regular.ttf"
style="normal"
weight=400

[[theme.fontFaces]]
family="Figtree"
url="app/static/Figtree-Medium.ttf"
style="normal"
weight=500

[[theme.fontFaces]]
family="Figtree"
url="app/static/Figtree-Semibold.ttf"
style="normal"
weight=600

[[theme.fontFaces]]
family="Figtree"
url="app/static/Figtree-Bold.ttf"
style="normal"
weight=600

[theme]
primaryColor="#3098E8"
backgroundColor="#0F1316"
secondaryBackgroundColor="#282E44"
textColor="#ECF3FB"
linkColor="#58a6ff"
borderColor="#ECF3FB"
showWidgetBorder=true
baseRadius="0.175rem"
showSidebarBorder=false
font="Figtree"
headingFont="Figtree"

[theme.sidebar]
backgroundColor="#507B9C"
textColor="#D9E8F7"
